# configure server port
server:
  port: 9090

# configure servlet context path
  servlet:
    context-path: /

spring:
  # configure data source and jpa
  datasource:
    driver-class-name: org.postgresql.Driver
    username: mbankingpostgres
    password: mbankingpostgres@123
    url: jdbc:postgresql://localhost:5432/mbankingdb
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

# configure spring mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: suonvicheak991@gmail.com
    password: ceno lwln bgvw jujv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# configure spring security
#  security:
#    user:
#      name: admin
#      password: admin@123

# configure classpath resources
resource:
  server-path: /static/
  client-path: /resources/**
