# configure server port
server:
  port: 8080

# configure servlet context path
  servlet:
    context-path: /

spring:
# configure data source and jpa
  datasource:
    driver-class-name: org.postgresql.Driver
    username: sbdemo
    password: sbdemo@123
    url: jdbc:postgresql://localhost:5432/mbankingdb
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

# configure spring mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: suonvicheak991@gmail.com
    password: ceno lwln bgvw jujv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# configure liquibase
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

# configure classpath resources
resource:
  server-path: /static/
  client-path: /resources/**

# configure swagger-ui custom path
springdoc:
  swagger-ui:
    path: /docs